export const extraServiceNames: string[] = [
  'AI Development',
  'Machine Learning Engineering',
  'MLOps',
  'Natural Language Processing (NLP)',
  'Computer Vision',
  'Chatbots & Virtual Assistants',
  'Retrieval-Augmented Generation (RAG)',
  'Vector Database Integration',
  'Prompt Engineering',
  'Generative AI Applications',
  'Data Engineering',
  'ETL & ELT Pipelines',
  'Business Intelligence (BI)',
  'Data Warehousing (Snowflake/BigQuery/Redshift)',
  'Data Modeling & DBT',
  'Workflow Orchestration (Airflow)',
  'Web Performance Optimization',
  'Core Web Vitals Remediation',
  'Accessibility (WCAG) Compliance',
  'Internationalization (i18n) & Localization (l10n)',
  'Programmatic SEO',
  'Schema Markup & Rich Results',
  'Digital PR & Outreach',
  'White-hat Link Building',
  'Content Strategy & Editorial',
  'Technical Copywriting',
  'A/B Testing & Experimentation',
  'Conversion Rate Optimization (CRO)',
  'Analytics Implementation (GA4)',
  'Tag Manager Instrumentation',
  'Customer Data Platform (CDP)',
  'Segment / RudderStack',
  'Email Deliverability',
  'CRM Integrations (HubSpot)',
  'CRM Integrations (Salesforce)',
  'Marketing Operations',
  'Product Design Workshops',
  'Design Systems',
  'Motion Design',
  'Illustration',
  'Brand Naming',
  'Discovery & Roadmapping',
  'Solution Architecture',
  'Security Hardening',
  'Penetration Testing (partner-led)',
  'SSO, SAML, OAuth2',
  'Payments Integration (Stripe)',
  'Payments Integration (PayPal/Braintree)',
  'Subscription Billing',
  'Checkout Optimization',
  'Heatmaps & Session Replay',
  'Observability (OpenTelemetry)',
  'Monitoring (Prometheus/Grafana)',
  'Logging (ELK/EFK)',
  'Incident Response & SRE',
  'Cost Optimization & FinOps',
  'Kubernetes & Docker',
  'Terraform & IaC',
  'Ansible & Configuration Management',
  'Helm & K8s Tooling',
  'Edge Computing & CDNs',
  'Vercel / Netlify Platforms',
  'AWS Amplify / Firebase / Supabase',
  'Authentication (Auth0/Clerk/NextAuth)',
  'Caching (Redis)',
  'Queues (RabbitMQ)',
  'Streaming (Kafka)',
  'Search (Elasticsearch)',
  'Search (Meilisearch/Algolia)',
  'Personalization Systems',
  'Recommendation Engines',
  'Multilingual SEO',
  'Regulatory Compliance (GDPR/CCPA)',
  'HIPAA Compliance (partner-led)',
  'PCI Compliance (partner-led)',
  'Performance Budgets & Governance',
  'Lighthouse & Lab/Field Testing',
  'Component Libraries & Storybook',
  'Unit Testing (Jest)',
  'E2E Testing (Playwright/Cypress)',
  'QA Automation',
  'API Gateways & Rate Limiting',
  'Serverless Apps',
  'Headless CMS Integrations',
  'Web Scraping & RPA',
  'Automation (Zapier/Make)',
  'Data Privacy & Consent Management',
  'Map & Geo Services',
  'Realtime Features (WebSockets)',
  'Push Notifications',
  'Offline-first Apps',
  'Microfrontends',
  'Monorepos & Tooling',
  'Code Quality & Linting',
  'Release Management',
  'Audits & Technical Due Diligence',
  'Training & Enablement',
  'Documentation & Knowledge Bases'
];


